### ISSUE TITLE
Fail to include v1.0.10 package using yarn

### ISSUE THREAD

**Issue by Fnxxxxo** [tecfu/smartwrap#2]
$ yarn add smartwrap
yarn add v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error http://registry.npm.taobao.org/smartwrap/download/smartwrap-1.0.10.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open 'd:\\yarn-cache\\v4\\npm-smartwrap-1.0.10-873ef350d4ee1262fed4a80a55634d86ae1faf48\\node_modules\\smartwrap\\e'"

**Comment by rexxars** [comment]
There appears to be a file called `ejq` in the root of the package which contains... A `git log` output?
It appears this file has some special characters in the filename, which is causing issues. When I downloaded it from unpkg, it was downloaded as `e_j_q`, though it was _listed_ as `ejq`. Either way, this should probably be removed and republished.

**Comment by Ryqsky** [comment]
First, `smartwrap` package  helped me a lot and thank tecfu.
Now, I have the same problem that fail to install v1.0.10 package.
This is due to the file `e\033j\033q` of smartwrap-1.0.10.tgz.
Please remove the file `e\033j\033q` and republish.
![image](https://user-images.githubusercontent.com/8382136/50500925-77eafa00-0a8f-11e9-93bd-3009859db811.png)

**Comment by tecfu** [comment]
Sorry for late response.  Removed file and updated dependencies in v 1.0.11. Should be fixed.
